# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: Task1/docs/source/conf.py

python:
  version: 3.6
  setup_py_install: true
  extra_requirements:
    - sphinxcontrib-napoleon
